### ISSUE TITLE
Add ClusterProfile (fka ClusterInventory) info to the SIG MC website

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes-sigs/sig-multicluster-site#19]
Add ClusterProfile project links to the Contributing section and high level documentation to the Overview section.

KEP issue: https://github.com/kubernetes/enhancements/pull/4323
KEP itself: https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/4322-cluster-inventory
API: https://github.com/kubernetes-sigs/cluster-inventory-api

/help

**Comment by zhiying-lin** [comment]
i'm willing to help to add the doc to the website. Thanks

**Comment by mikeshng** [comment]
assign @zhiying-lin
