### ISSUE TITLE
Set up deployment pipeline for this repo's site

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes-sigs/sig-multicluster-site#4]
Per the README, and in the proposal site, we would deploy from local using the directions on the [mkdocs website](https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages). The Gateway API website appears to use netlify  instead (https://github.com/kubernetes-sigs/gateway-api/pull/559) and this also appears to be how they got proper DNS resolution from `*.k8s.io` so I would like us to do that. Determine if we want to do the same; otherwise set up GitHub Actions to deploy automatically on a merge into the `main` branch.

**Comment by jmhbnz** [comment]
Hey @lauralorenz - I'm keen to support sig-multicluster. I have raised a pr with some ideas on initial scaffolding for building the site via netlify  🙏🏻

**Comment by lauralorenz** [comment]
Awesome thank you @jmhbnz !!!!

**Comment by jmhbnz** [comment]
Hey @lauralorenz with the initial scaffolding for `netlify.toml` merged do we have an issue open for step two?

I'm happy to raise if not, looking at the [template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-integration&template=site-request.yml&title=REQUEST%3A+Netlify+site+for+%3Crepo%3E) it looks like we just need to supply two values, here is what I would propose:

**Repository**
- `kubernetes-sigs/sig-multicluster-site`


**Project domain**
- `*.multicluster.sigs.k8s.io`

**Comment by npintaux** [comment]
Hi @jmhbnz , I have just raised the [issue](https://github.com/kubernetes/org/issues/4086) per your recommendation.
As I am learning the intricacies of k8s OSS projects on GitHub, is there anything I need to do? I saw in other issues that some people were assigning mrbobbytables to them.

**Comment by lauralorenz** [comment]
@mrbobbytables took a very quick look and said a better template for our netlify.toml would be [this one in kueue](https://github.com/kubernetes-sigs/kueue/blob/main/netlify.toml). Basically we don't need the redirects in the netlify.toml (the ones in the Gateway example are out of date as netlify actually switched from netlify.com to netlify.app, and whatever netlify might have needed in the past to detect the proper prod branch is apparently no longer needed) so we can take those out. 

For the actual netlify issue now that it's raised we need a github admin to help us, I'm poking around on [slack some too](https://kubernetes.slack.com/archives/C1TU9EB9S/p1678891146297969) to see if we can get in someone's TODO list any time soon :) Thank you @jmhbnz and @npintaux !!

**Comment by jmhbnz** [comment]
Thanks for the feedback @lauralorenz - I've raised #7 to tidy up those unnecessary redirects and also streamline the local environment setup for the site.

Fingers crossed we can get the netlify domain setup soon! 🙏🏻

**Comment by jmhbnz** [comment]
Great news - have raised our dns request here to get the CNAME for the new netlify address: https://github.com/kubernetes/k8s.io/issues/4991

**Comment by jmhbnz** [comment]
Hey @lauralorenz - Site pipeline is done along with dns, all running nicely here: https://multicluster.sigs.k8s.io

I think we can close this now? 🙏🏻

**Comment by lauralorenz** [comment]
Yes all looks good and we successfully had a merge and redeploy all work too! YAY! Thank you everyone!!!

/close
